spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL_DB:jdbc:mysql://localhost/foro }
    username: ${USER_DB:root }
    password: ${PASSWORD_DB:Admin1234 }

hibernate:
  hbm2ddl:
    auto: create

api:
  security:
    secret: ${SECRET_KEY:algoSecreto}