server:
  port: ${PORT:8080}
#  servlet:
#    context-path: /swagger-ui.html

spring:
  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL_DB:jdbc:mysql://localhost/foro}
    username: ${USER_DB:root}
    password: ${PASSWORD_DB:Admin1234}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    url: https://foroalura-production.up.railway.app

api:
  security:
    secret: ${SECRET_KEY:algoSecreto}

